name: Build Calculator_NX

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkita64_devkitarm

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      
      - name: Get libraries
        run: |
          sudo dkp-pacman -Syu
          sudo dkp-pacman -S switch-dev
          sudo dkp-pacman -S switch-glfw switch-mesa switch-glm
      
      - name: Build Calculator_NX
        run: |
          make -j$(nproc)
          
    

