name: Build Calculator_NX

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkita64_devkitarm

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: make -j$(nproc)
        
      - uses: actions/upload-artifact@master
        with:
          name: Calculator_NX
          path: Calculator_NX.nro
